name = "multichannelbroadcast"
pages_build_output_dir = "./dist"

[[services]]
binding = "MCB_CRAWLER"
service = "mcb-crawler"

[[env.preview.services]]
binding = "MCB_CRAWLER"
service = "mcb-crawler-preview"
